### ISSUE TITLE
服务启动时如果连不上telegram服务器似乎不会再次检测是否可以连接？

### ISSUE THREAD

**Issue by EnnawYang** [HouCoder/tele-aria2#19]
环境：openwrt，Docker
在openwrt中代理服务比docker启动稍晚一点，所以docker容器刚启动的时候是连不上tg服务器的，还要手动重启下容器才能重新连接

**Comment by HouCoder** [comment]
会尝试自动重连几次的，实在不行那就在 docker compose 里面加上 depends_on 参数。
