### ISSUE TITLE
请加入中文。

### ISSUE THREAD

**Issue by ReddotCleaner** [HouCoder/tele-aria2#9]
虽然之后简单的几句和几个简单的词，但如果能加入中文会看来舒服点，如果没计划的话我自己改改就好，如果有需要，我可以帮忙翻译好"Telegram.ts"文本给你。

**Comment by HouCoder** [comment]
感谢建议，我以前也考虑过，但是这个暂时不在 roadmap 里面，如果要加入中文的支持的话我希望一次做全面了，包括中文的提示消息、cli 帮助内容和文档内容，个人不太喜欢有的地方有中文有的地方没有中文这种方案。全面中文会占用不少时间，现在手里还有其它是要处理。

英文内容应该挺简单的，基本功能用起来对于国内的开发者来说应该没有什么太大的障碍。
